### ISSUE TITLE
<template_dir>/build: no such file or directory

### ISSUE THREAD

**Issue by MatthewRDodds** [jfrolich/smoothie#1]
When adding smoothie to my project I added the following config:

```elixir
config :smoothie, template_dir: Path.join(["web", "templates", "email"])
```

But when I try to run `mix deps.compile smoothie` I get a compilation error on [lib/smoothie.ex:15](https://github.com/jfrolich/smoothie/blob/master/lib/smoothie.ex#L13-L15). It seems to be appending `build` to the `template_dir`path but I couldn't find anything about this in the documentation.

**Comment by jfrolich** [comment]
Awesome you are using Smoothie. We are using it in production and it is really stable, but I just released it as a library so the developer experience might not be great yet.

It is right that the app does not compile if the directory does not exists, but it seems that you have the directory.

Let me write a test case for this, and see if I get the same issue! Are you using Phoenix?

Cheers,

Jaap

**Comment by MatthewRDodds** [comment]
Thanks @jfrolich! I don't know why I didn't think to try that.

**Comment by stephenmoloney** [comment]
potential fix? [PR](https://github.com/jfrolich/smoothie/pull/2)

**Comment by MatthewRDodds** [comment]
I tested this fix locally and can confirm that my app compiles now and automatically generates the build directory.
