### ISSUE TITLE
Html only option doesn't seem to work

### ISSUE THREAD

**Issue by RobinClowers** [jfrolich/smoothie#19]
I just upgraded to smoothie 3.1.1, and I've trie both the config option (`config :smoothie, html_only: true`) and the command line flag (`mix smoothie.compile --html-only`), but in all cases I still get text templates being generated.

**Comment by RobinClowers** [comment]
I didn't realize I needed to run `mix smoothie.init` again to update the node package... Maybe you could check the version of that package on boot or something? In any case, this feature works fine now.

**Comment by jfrolich** [comment]
Great idea to check the package version. That would solve a lot of issues indeed 👍
