### ISSUE TITLE
allow for multiple smoothie configurations

### ISSUE THREAD

**Issue by stephenmoloney** [jfrolich/smoothie#3]
#### problem:
Project might have more than one smoothie layout for different email purposes

#### potential solution
Allow smoothie to be configured for multiple template_directories and multiple layouts.

***Note:***
I've made some progress towards this ... it has required work on `elixir-smoothie` too, I've a bit more to go on this but I think it would be an enhancement.

Let me know what you think...

[Smoothie Reference branch](https://github.com/stephenmoloney/smoothie/tree/multiple-smoothies)
[Elixir Smoothie Reference branch](https://github.com/stephenmoloney/elixir-smoothie/tree/foundation-emails)

Edit:

See PR.. https://github.com/jfrolich/smoothie/pull/4
and companion PR  https://github.com/jfrolich/elixir-smoothie

**Comment by jfrolich** [comment]
This is now possible in 2.0.0
