### ISSUE TITLE
compilation deadlock issue

### ISSUE THREAD

**Issue by stephenmoloney** [jfrolich/smoothie#7]
@jfrolich 
I think I'm getting a compilation dealock issue but I can't be sure since I'm finding it difficult to reproduce...

Have you tried running `mix do clean, deps.clean smoothie, deps.get smoothie, compile && mix smoothie.compile` in your project without any issue?

Hopefully I can figure this out soon. Sorry, I can't be more specific for now.

**Comment by stephenmoloney** [comment]
The issue I was having was that when the project was cleaned with `mix clean` and then mix compile` was subsequently run, the `template_email` and `template_text` functions would not be available blocking further compilation.

I think this PR fixes those issues.
https://github.com/jfrolich/smoothie/pull/6/commits/0116c48fc91448a5cd6706aa6bb86c147b4e9d0b

**Comment by jfrolich** [comment]
Yes, indeed an edge case I didn't test for! Thanks for the PR!
